version: '3'
services:
  weasyprint-aspnet-core:
    image: weasyprint/aspnet-core:${DOTNET_VERSION}-${WEASYPRINT_VERSION}
    build:
      context: .
      args:
        DOTNET_VERSION: ${DOTNET_VERSION}
        WEASYPRINT_VERSION: ${WEASYPRINT_VERSION}
